name: vfxmoney
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  flutter_bloc: ^9.1.1
  go_router: ^17.0.0
  firebase_auth: ^6.1.2
  go_transitions: ^0.8.3
  equatable: ^2.0.7
  device_info_plus: ^12.2.0
  get_it: ^9.1.0
  shared_preferences: ^2.5.3
  socket_io_client: ^3.1.2
  uuid: ^4.5.2
  fpdart: ^1.2.0
  flutter_svg: ^2.2.3
  image_picker: ^1.2.1
  fluttertoast: ^9.0.0
  connectivity_plus: ^7.0.0
  curved_navigation_bar: ^1.0.6
  flutter_launcher_icons: ^0.14.4   # <-- Added here
  dart_jsonwebtoken: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# -------------------------------
# Flutter Launcher Icons Config
# -------------------------------
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_logo.png"   # <--- Change path if needed
  min_sdk_android: 21

# -------------------------------
# Flutter app section
# -------------------------------
flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: HubotSans
      fonts:
        - asset: assets/fonts/HubotSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/HubotSans-SemiBold.ttf
          weight: 600

    - family: JetBrainsMono
      fonts:
        - asset: assets/fonts/JetBrainsMono-Regular.ttf
          weight: 400
        - asset: assets/fonts/JetBrainsMono-Medium.ttf
          weight: 500
